apiVersion: v1
kind: PersistentVolume
metadata:
  name: chartmuseum-pv-hostpath
  labels:
    component: chartmuseum
    release: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: "8Gi"
  claimRef:
    name: {{ .Release.Name }}-chartmuseum
    namespace: {{ .Release.Namespace }}
  hostPath:
    path: "/testops/local/chartmuseum/"
  persistentVolumeReclaimPolicy: Retain
