apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-registry-pv-hostpath
  labels:
    component: docker-registry
    release: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: "50Gi"
  claimRef:
    name: {{ .Release.Name }}-docker-registry
    namespace: {{ .Release.Namespace }}
  hostPath:
    path: "/testops/local/docker-registry/"
  persistentVolumeReclaimPolicy: Retain
