
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-master-pvclaim
  labels:
    app: jenkins-master
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "50Gi"