apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jenkins-master
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: "50Gi"
  claimRef:
    name: jenkins-master-pvclaim
    namespace: default
  hostPath:
    path: "/testops/local/jenkins/"
  persistentVolumeReclaimPolicy: Retain
