apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv-hostpath
  labels:
    app.kubernetes.io/name: prometheus
    release: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
    heritage: {{ .Release.Service }}
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: prometheus-monitoring-prometheus-db-prometheus-monitoring-prometheus-0
    namespace: {{ .Release.Namespace }}
  hostPath:
    path: "/testops/local/prometheus/"
  persistentVolumeReclaimPolicy: Retain